use_frameworks!

platform :ios, '8.0'

target 'GYDB_Example' do
  pod 'FMDB'
  pod 'MyLayout'
  pod 'TPKeyboardAvoiding'

  target 'GYDB_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
